import 'package:isar_community/isar.dart';

// The Isar generator requires a part file for code generation.
// This file will be generated by build_runner.
// Run command : flutter pub run build_runner build 
part 'm_student.g.dart';

// ----------------------------
// Subject (Embedded Class)
// ----------------------------

@embedded
class Subject {
  // Name of the subject (e.g., Math, Science)
  late String name;

  // Marks scored in that specific subject
  late double mark;
}

// ----------------------------
// Student Collection Schema
// ----------------------------

// The @collection annotation marks this class as an Isar collection (table).
@collection
class Student {
  // Auto-increment ID generated by Isar
  Id id = Isar.autoIncrement;

  // Name of the student
  late String name;

  // Age of the student
  late double age;

  // List of subjects and corresponding marks stored as an embedded list.
  // (Isar does NOT support Map<String, double>, so this is the correct format)
  late List<Subject> marks;

  // Convenience getter to create a readable summary for UI
  // Converts:
  //  [Subject("Math", 95), Subject("Science", 88)]
  // Into:
  //  "Math: 95.0, Science: 88.0"
  String get marksSummary {
    if (marks.isEmpty) return 'No marks recorded';
    return marks
        .map((e) => '${e.name}: ${e.mark.toStringAsFixed(1)}')
        .join(', ');
  }
}
